services:
  app:
    build:
      context: .
    image: next-template
    container_name: next-template
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "yarn dev"

volumes:
  node_modules:
