services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: next-template
    container_name: next-template
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    restart: always
    tty: true
    stdin_open: true

volumes:
  node_modules:
