services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: next-template
    container_name: next-template
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: always
    command: sh -c "yarn dev"

volumes:
  node_modules:
